{
  "loc.friendlyName": "Python pip 認証",
  "loc.helpMarkDown": "[Learn more about this task](https://docs.microsoft.com/azure/devops/pipelines/tasks/package/pip-authenticate) or [see the pip documentation](https://pip.pypa.io/en/stable/reference/pip_install/)",
  "loc.description": "Python ディストリビューションのインストールに使用される pip クライアントの認証タスク",
  "loc.instanceNameFormat": "Pip Authenticate",
  "loc.group.displayName.feedAuthentication": "フィードと認証",
  "loc.input.label.artifactFeeds": "マイ フィード (以下を選択)",
  "loc.input.help.artifactFeeds": "この組織内に存在する、認証対象のフィードを選択します",
  "loc.input.label.pythonDownloadServiceConnections": "外部組織からのフィード",
  "loc.input.help.pythonDownloadServiceConnections": "この組織の外部で認証するエンドポイントを選択します。",
  "loc.input.label.onlyAddExtraIndex": "Don't set primary index URL",
  "loc.input.help.onlyAddExtraIndex": "If this is set to true, no feed will be set as the primary index URL. All of the configured feeds/endpoints will be set as extra index URLs. Defaults to false.",
  "loc.messages.Info_AddingInternalFeeds": "%s 内部フィードの認証情報を追加しています。",
  "loc.messages.Info_AddingExternalFeeds": "%s 外部エンドポイントの認証情報を追加しています。",
  "loc.messages.Info_SuccessAddingAuth": "%s の内部フィードと %s の外部エンドポイントに認証が正常に追加されました。",
  "loc.messages.Info_AddingPasswordAuthEntry": "フィード %s のユーザー名パスワード認証エントリを追加しています",
  "loc.messages.Info_AddingTokenAuthEntry": "フィード %s のトークン認証エントリを追加しています",
  "loc.messages.Error_FailedToParseFeedUrlAndAuth": "フィード URL の解析および認証情報の追加に失敗しました。%s",
  "loc.messages.FailedToGetPackagingUri": "既定のコレクション URI を使用して、パッケージ URI を取得できません。",
  "loc.messages.FailedToAddAuthentication": "認証を追加できませんでした。",
  "loc.messages.Warn_TooManyFeedEntries": "認証のフィード エントリが多すぎます。タスク内のリポジトリの数を減らしてください。",
  "loc.messages.Warning_SessionCreationFailed": "Could not create provenance session: %s"
}