{
  "loc.friendlyName": "Python pip 身份验证",
  "loc.helpMarkDown": "[详细了解此任务](https://pip.pypa.io/en/stable/reference/pip_install/)或[参阅 pip 文档](https://pip.pypa.io/)",
  "loc.description": "用于安装 Python 分发版的 pip 客户端的身份验证任务",
  "loc.instanceNameFormat": "Pip 身份验证 $(message)",
  "loc.group.displayName.feedAuthentication": "源和身份验证",
  "loc.input.label.feedList": "我的源(在下方选择)",
  "loc.input.help.feedList": "选择要在此组织中进行身份验证的源",
  "loc.input.label.externalSources": "来自外部组织的源",
  "loc.input.help.externalSources": "选择要在此组织外部进行身份验证的终结点。",
  "loc.messages.Info_AddingInternalFeeds": "正在为 %s 内部源添加身份验证信息。",
  "loc.messages.Info_AddingExternalFeeds": "正在为 %s 外部终结点添加身份验证信息。",
  "loc.messages.Info_SuccessAddingAuth": "已成功添加对 %s 内部源和 %s 外部终结点的身份验证。",
  "loc.messages.Info_AddingPasswordAuthEntry": "正在为源 %s 添加用户名密码身份验证条目",
  "loc.messages.Info_AddingTokenAuthEntry": "正在为源 %s 添加令牌身份验证条目",
  "loc.messages.Error_FailedToParseFeedUrlAndAuth": "未能分析源 URL 和添加身份验证信息。%s",
  "loc.messages.FailedToGetPackagingUri": "无法使用默认集合 URI 获取打包 URI。",
  "loc.messages.FailedToAddAuthentication": "添加身份验证失败。",
  "loc.messages.FeedTokenUnavailable": "未能获取此组织的访问令牌。",
  "loc.messages.Warn_TooManyFeedEntries": "身份验证的源条目过多。请减少任务中的存储库数。",
  "loc.messages.Warning_SessionCreationFailed": "无法创建出处会话: %s"
}