{
  "loc.friendlyName": "Python pip authenticate",
  "loc.helpMarkDown": "[Learn more about this task](https://pip.pypa.io/en/stable/reference/pip_install/) or [see the pip documentation](https://pip.pypa.io/)",
  "loc.description": "Authentication task for the pip client used for installing Python distributions",
  "loc.instanceNameFormat": "Pip Authenticate $(message)",
  "loc.group.displayName.feedAuthentication": "Feeds and Authentication",
  "loc.input.label.feedList": "My feeds (select below)",
  "loc.input.help.feedList": "Select feeds to authenticate present in this organization",
  "loc.input.label.externalSources": "Feeds from external organizations",
  "loc.input.help.externalSources": "Select endpoints to authenticate outside this organization.",
  "loc.messages.Info_AddingInternalFeeds": "Adding auth information for %s internal feed(s).",
  "loc.messages.Info_AddingExternalFeeds": "Adding auth information for %s external endpoint.",
  "loc.messages.Info_SuccessAddingAuth": "Successfully added auth for %s internal feeds and %s external endpoint.",
  "loc.messages.Info_AddingPasswordAuthEntry": "Adding username password auth entry for feed %s",
  "loc.messages.Info_AddingTokenAuthEntry": "Adding token auth entry for feed %s",
  "loc.messages.Error_FailedToParseFeedUrlAndAuth": "Failed to parse the feed url and add auth information. %s",
  "loc.messages.FailedToGetPackagingUri": "Unable to get packaging uri, using default collection uri.",
  "loc.messages.FailedToAddAuthentication": "Failed to add authentication.",
  "loc.messages.FeedTokenUnavailable": "Failed to get the access token for this organization.",
  "loc.messages.Warn_TooManyFeedEntries": "Too many feed entries for auth. Please reduce the number of repositories in the task.",
  "loc.messages.Warning_SessionCreationFailed": "Could not create provenance session: %s"
}