{
  "loc.friendlyName": "Python-PIP-Authentifizierung",
  "loc.helpMarkDown": "[Learn more about this task](https://pip.pypa.io/en/stable/reference/pip_install/) or [see the pip documentation](https://pip.pypa.io/)",
  "loc.description": "Authentifizierungsaufgabe für den PIP-Client, der zum Installieren von Python-Distributionen verwendet wird",
  "loc.instanceNameFormat": "PIP-Authentifizierung: $(message)",
  "loc.group.displayName.feedAuthentication": "Feeds und Authentifizierung",
  "loc.input.label.feedList": "Meine Feeds (Auswahl unten)",
  "loc.input.help.feedList": "Wählen Sie Feeds für die Authentifizierung innerhalb dieser Organisation aus.",
  "loc.input.label.externalSources": "Feeds aus externen Organisationen",
  "loc.input.help.externalSources": "Wählen Sie Endpunkte für die Authentifizierung außerhalb dieser Organisation aus.",
  "loc.messages.Info_AddingInternalFeeds": "Authentifizierungsinformationen für %s interne Feeds werden hinzugefügt.",
  "loc.messages.Info_AddingExternalFeeds": "Authentifizierungsinformationen für den externen Endpunkt \"%s\" werden hinzugefügt.",
  "loc.messages.Info_SuccessAddingAuth": "Die Authentifizierung für %s interne Feeds und %s externen Endpunkt wurde erfolgreich hinzugefügt.",
  "loc.messages.Info_AddingPasswordAuthEntry": "Eintrag zur Authentifizierung über Benutzername/Kennwort für Feed \"%s\" wird hinzugefügt.",
  "loc.messages.Info_AddingTokenAuthEntry": "Eintrag zur Authentifizierung über ein Token für Feed \"%s\" wird hinzugefügt.",
  "loc.messages.Error_FailedToParseFeedUrlAndAuth": "Fehler beim Analysieren der Feed-URL und beim Hinzufügen von Authentifizierungsinformationen. %s",
  "loc.messages.FailedToGetPackagingUri": "Der URI für die Paketierung kann nicht mithilfe des URI der Standardsammlung abgerufen werden.",
  "loc.messages.FailedToAddAuthentication": "Fehler beim Hinzufügen der Authentifizierung.",
  "loc.messages.FeedTokenUnavailable": "Fehler beim Abrufen des Zugriffstokens für diese Organisation.",
  "loc.messages.Warn_TooManyFeedEntries": "Zu viele Feedeinträge für die Authentifizierung. Verringern Sie die Anzahl von Repositorys in der Aufgabe.",
  "loc.messages.Warning_SessionCreationFailed": "Die Herkunftssitzung konnte nicht erstellt werden: %s"
}